name: Setup Environment
description: 'Sets up Python and installs dependencies using uv'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install project dependencies
      shell: bash
      run: uv sync --all-extras --dev
