# pylint: skip-file
"""Add creator to game.

Revision ID: 03e2e144b1f0
Revises: 3a4c3fe0b5ba
Create Date: 2025-05-04 23:34:18.642729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03e2e144b1f0'
down_revision: Union[str, None] = '3a4c3fe0b5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_game_creator_id_tg_user'), 'game', 'tg_user', ['creator_id'], ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_game_creator_id_tg_user'), 'game', type_='foreignkey')
    op.drop_column('game', 'creator_id')
    # ### end Alembic commands ###
