# pylint: skip-file
"""Cascade delete munchkin.

Revision ID: 071222030e8a
Revises: ecade2e1f5eb
Create Date: 2025-05-05 21:40:22.063890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '071222030e8a'
down_revision: Union[str, None] = 'ecade2e1f5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_munchkin_game_id_game', 'munchkin', type_='foreignkey')
    op.create_foreign_key(op.f('fk_munchkin_game_id_game'), 'munchkin', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_munchkin_game_id_game'), 'munchkin', type_='foreignkey')
    op.create_foreign_key('fk_munchkin_game_id_game', 'munchkin', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###
