# pylint: skip-file
"""Cascade ban munchkins.

Revision ID: 0d23fb62182b
Revises: cf9516bab062
Create Date: 2025-05-06 09:29:00.499868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d23fb62182b'
down_revision: Union[str, None] = 'cf9516bab062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bannedmunchkin_game_id_game', 'bannedmunchkin', type_='foreignkey')
    op.drop_constraint('fk_bannedmunchkin_user_id_tg_user', 'bannedmunchkin', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bannedmunchkin_game_id_game'), 'bannedmunchkin', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_bannedmunchkin_user_id_tg_user'), 'bannedmunchkin', 'tg_user', ['user_id'], ['tg_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bannedmunchkin_user_id_tg_user'), 'bannedmunchkin', type_='foreignkey')
    op.drop_constraint(op.f('fk_bannedmunchkin_game_id_game'), 'bannedmunchkin', type_='foreignkey')
    op.create_foreign_key('fk_bannedmunchkin_user_id_tg_user', 'bannedmunchkin', 'tg_user', ['user_id'], ['tg_id'])
    op.create_foreign_key('fk_bannedmunchkin_game_id_game', 'bannedmunchkin', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###
