# pylint: skip-file
"""Init

Revision ID: 284bdc00f806
Revises: 
Create Date: 2025-04-21 13:17:17.527848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '284bdc00f806'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tg_group',
        sa.Column('tg_id',
                  sa.BigInteger(),
                  autoincrement=False,
                  nullable=False),
        sa.Column('name',
                  sqlmodel.sql.sqltypes.AutoString(length=32),
                  nullable=False), sa.PrimaryKeyConstraint('tg_id'),
        sa.UniqueConstraint('name'))
    op.create_table(
        'tg_user',
        sa.Column('tg_id',
                  sa.BigInteger(),
                  autoincrement=False,
                  nullable=False),
        sa.Column('user_name',
                  sqlmodel.sql.sqltypes.AutoString(length=32),
                  nullable=False),
        sa.Column('full_name',
                  sqlmodel.sql.sqltypes.AutoString(length=128),
                  nullable=False), sa.PrimaryKeyConstraint('tg_id'),
        sa.UniqueConstraint('full_name'), sa.UniqueConstraint('user_name'))
    op.create_table(
        'game', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('on_going', sa.Boolean(), nullable=False),
        sa.Column('current_player_number', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['tg_group.tg_id'],
        ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('tg_user')
    op.drop_table('tg_group')
    # ### end Alembic commands ###
