# pylint: skip-file
"""Munchkin

Revision ID: 6bdf256496c6
Revises: 284bdc00f806
Create Date: 2025-04-21 19:47:27.927982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bdf256496c6'
down_revision: Union[str, None] = '284bdc00f806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('KICK_DOOR', 'LOOK_TROUBLE', 'LOOT_ROOM', 'CHARITY', 'COMBAT', name='turntype').create(op.get_bind())
    sa.Enum('MALE', 'FEMALE', name='gender').create(op.get_bind())
    op.create_table('munchkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', name='gender', create_type=False), nullable=True),
    sa.Column('number', sa.SmallInteger(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('strength', sa.SmallInteger(), nullable=True),
    sa.Column('luck', sa.SmallInteger(), nullable=True),
    sa.Column('runaway_bonus', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('munchkin_id', sa.Integer(), nullable=False),
    sa.Column('turn_type', postgresql.ENUM('KICK_DOOR', 'LOOK_TROUBLE', 'LOOT_ROOM', 'CHARITY', 'COMBAT', name='turntype', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['munchkin_id'], ['munchkin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turn')
    op.drop_table('munchkin')
    sa.Enum('MALE', 'FEMALE', name='gender').drop(op.get_bind())
    sa.Enum('KICK_DOOR', 'LOOK_TROUBLE', 'LOOT_ROOM', 'CHARITY', 'COMBAT', name='turntype').drop(op.get_bind())
    # ### end Alembic commands ###
