# pylint: skip-file
"""Game code.

Revision ID: 74adcbf8ca95
Revises: 03e2e144b1f0
Create Date: 2025-05-05 09:36:20.882384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74adcbf8ca95'
down_revision: Union[str, None] = '03e2e144b1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(op.f('uq_game_code'), 'game', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_game_code'), 'game', type_='unique')
    op.drop_column('game', 'code')
    # ### end Alembic commands ###
