# pylint: skip-file
"""The last

Revision ID: 81de717a5c61
Revises: dd6c994e59e5
Create Date: 2025-04-23 12:07:49.518314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81de717a5c61'
down_revision: Union[str, None] = 'dd6c994e59e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actionmonster',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], name=op.f('fk_actionmonster_action_id_action')),
    sa.ForeignKeyConstraint(['monster_id'], ['monster.card_id'], name=op.f('fk_actionmonster_monster_id_monster')),
    sa.PrimaryKeyConstraint('action_id', 'monster_id', name=op.f('pk_actionmonster'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actionmonster')
    # ### end Alembic commands ###
