# pylint: skip-file
"""Lost foreign keys.

Revision ID: 898411677ea2
Revises: 74adcbf8ca95
Create Date: 2025-05-05 09:58:23.242600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "898411677ea2"
down_revision: Union[str, None] = "74adcbf8ca95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "item", "item_type_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "item", "item_property_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column(
        "stats", sa.Column("stats_type_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_stats_stats_type_id_statstype"),
        "stats",
        "statstype",
        ["stats_type_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_stats_stats_type_id_statstype"), "stats", type_="foreignkey"
    )
    op.drop_column("stats", "stats_type_id")
    op.alter_column(
        "item", "item_property_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "item", "item_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
