# pylint: skip-file
"""Cascade delete game and munchkins.

Revision ID: c27c62fa0c9c
Revises: 071222030e8a
Create Date: 2025-05-05 21:52:56.016220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c27c62fa0c9c'
down_revision: Union[str, None] = '071222030e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_game_creator_id_tg_user', 'game', type_='foreignkey')
    op.create_foreign_key(op.f('fk_game_creator_id_tg_user'), 'game', 'tg_user', ['creator_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_constraint('fk_munchkin_user_id_tg_user', 'munchkin', type_='foreignkey')
    op.create_foreign_key(op.f('fk_munchkin_user_id_tg_user'), 'munchkin', 'tg_user', ['user_id'], ['tg_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_munchkin_user_id_tg_user'), 'munchkin', type_='foreignkey')
    op.create_foreign_key('fk_munchkin_user_id_tg_user', 'munchkin', 'tg_user', ['user_id'], ['tg_id'])
    op.drop_constraint(op.f('fk_game_creator_id_tg_user'), 'game', type_='foreignkey')
    op.create_foreign_key('fk_game_creator_id_tg_user', 'game', 'tg_user', ['creator_id'], ['tg_id'])
    # ### end Alembic commands ###
