# pylint: skip-file
"""Ban munchkins.

Revision ID: cf9516bab062
Revises: c27c62fa0c9c
Create Date: 2025-05-06 09:14:35.960679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf9516bab062'
down_revision: Union[str, None] = 'c27c62fa0c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bannedmunchkin',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_bannedmunchkin_game_id_game')),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.tg_id'], name=op.f('fk_bannedmunchkin_user_id_tg_user')),
    sa.PrimaryKeyConstraint('game_id', 'user_id', name=op.f('pk_bannedmunchkin'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bannedmunchkin')
    # ### end Alembic commands ###
