# pylint: skip-file
"""Test2

Revision ID: dab928213de7
Revises: 6bdf256496c6
Create Date: 2025-04-21 20:03:02.929703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dab928213de7'
down_revision: Union[str, None] = '6bdf256496c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('difference', sa.SmallInteger(), nullable=True),
    sa.Column('munchkin_can_join', sa.Boolean(), nullable=False),
    sa.Column('monster_can_join', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_runaway', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('munchkincombat',
    sa.Column('munchkin_id', sa.Integer(), nullable=False),
    sa.Column('combat_id', sa.Integer(), nullable=False),
    sa.Column('modifier', sa.SmallInteger(), nullable=True),
    sa.Column('runaway_bonus', sa.SmallInteger(), nullable=True),
    sa.Column('is_helping', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['combat_id'], ['combat.id'], ),
    sa.ForeignKeyConstraint(['munchkin_id'], ['munchkin.id'], ),
    sa.PrimaryKeyConstraint('munchkin_id', 'combat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('munchkincombat')
    op.drop_table('combat')
    # ### end Alembic commands ###
