# pylint: skip-file
"""fix1

Revision ID: e136fc120501
Revises: ae56d122db5d
Create Date: 2025-04-22 11:31:54.405465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "e136fc120501"
down_revision: Union[str, None] = "ae56d122db5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "card", "description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "gameitem", "description", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "item", "description", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "item", "description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "gameitem", "description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "card", "description", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
