# pylint: skip-file
"""Проверка на уникальность user_id и game_id

Revision ID: efaebf42bebf
Revises: dab928213de7
Create Date: 2025-04-21 21:15:39.827991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'efaebf42bebf'
down_revision: Union[str, None] = 'dab928213de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'munchkin', ['user_id', 'game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'munchkin', type_='unique')
    # ### end Alembic commands ###
